//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolEditor.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Editor.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Cool Editor.
        /// </summary>
        public static string Buy_caption {
            get {
                return ResourceManager.GetString("Buy_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We really hope you can buy this app to support us to make it better..
        /// </summary>
        public static string Buy_message {
            get {
                return ResourceManager.GetString("Buy_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry this file cannot be opened. :-(. Would you mind send this file to me at landxh@gmail.com?.
        /// </summary>
        public static string Can_not_open {
            get {
                return ResourceManager.GetString("Can_not_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Clear_all {
            get {
                return ResourceManager.GetString("Clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to log in.
        /// </summary>
        public static string Click_to_login {
            get {
                return ResourceManager.GetString("Click_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue trial.
        /// </summary>
        public static string Continue_trial {
            get {
                return ResourceManager.GetString("Continue_trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all.
        /// </summary>
        public static string Copy_all {
            get {
                return ResourceManager.GetString("Copy_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard..
        /// </summary>
        public static string Copy_success {
            get {
                return ResourceManager.GetString("Copy_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Copy_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new file.
        /// </summary>
        public static string Create_caption {
            get {
                return ResourceManager.GetString("Create_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the file name (egg. abc.xml).
        /// </summary>
        public static string Create_message {
            get {
                return ResourceManager.GetString("Create_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to Ace Project, which is the core of this app..
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete all files..
        /// </summary>
        public static string Delete_all_fail {
            get {
                return ResourceManager.GetString("Delete_all_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all files?!.
        /// </summary>
        public static string Delete_all_message {
            get {
                return ResourceManager.GetString("Delete_all_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files deleted..
        /// </summary>
        public static string Delete_all_success {
            get {
                return ResourceManager.GetString("Delete_all_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete.
        /// </summary>
        public static string Delete_comfirm {
            get {
                return ResourceManager.GetString("Delete_comfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed..
        /// </summary>
        public static string Delete_fail {
            get {
                return ResourceManager.GetString("Delete_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted successfully..
        /// </summary>
        public static string Delete_success {
            get {
                return ResourceManager.GetString("Delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Editor is a text editor enabling you to view and edit code files on your Windows Phone and share it easily..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail :-(.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Editor Feedback.
        /// </summary>
        public static string Feedback_mail_title {
            get {
                return ResourceManager.GetString("Feedback_mail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string Font_size {
            get {
                return ResourceManager.GetString("Font_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input URL to download file.
        /// </summary>
        public static string Input_url_to_download {
            get {
                return ResourceManager.GetString("Input_url_to_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL or it does not exist..
        /// </summary>
        public static string Invalid_url {
            get {
                return ResourceManager.GetString("Invalid_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string Last_modified {
            get {
                return ResourceManager.GetString("Last_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync.
        /// </summary>
        public static string Last_sync {
            get {
                return ResourceManager.GetString("Last_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Log_off {
            get {
                return ResourceManager.GetString("Log_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error, Please try again later..
        /// </summary>
        public static string Network_error {
            get {
                return ResourceManager.GetString("Network_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No change detected..
        /// </summary>
        public static string No_change {
            get {
                return ResourceManager.GetString("No_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no, no file here....
        /// </summary>
        public static string No_file {
            get {
                return ResourceManager.GetString("No_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file is coming, do not play joke with me. :-(.
        /// </summary>
        public static string No_file_coming {
            get {
                return ResourceManager.GetString("No_file_coming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Onedrive does not contain &quot;revision&quot; property, Cool Editor does not provide auto sync function. You need to manually sync file from Onedrive by long pressing the file item and choosing &quot;Upload and ...&quot; or &quot;Download and ...&quot;. Sorry for inconvenience..
        /// </summary>
        public static string notice_20140819_body {
            get {
                return ResourceManager.GetString("notice_20140819_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice about sync button.
        /// </summary>
        public static string notice_20140819_caption {
            get {
                return ResourceManager.GetString("notice_20140819_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string notice_20140819_left {
            get {
                return ResourceManager.GetString("notice_20140819_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark read.
        /// </summary>
        public static string notice_20140819_right {
            get {
                return ResourceManager.GetString("notice_20140819_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The online file is missing.
        /// </summary>
        public static string online_file_missing {
            get {
                return ResourceManager.GetString("online_file_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am currently working on it, if you have any suggestion on it, send me Email and tell me about it. I hope we can make it better..
        /// </summary>
        public static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit?.
        /// </summary>
        public static string Quit_message {
            get {
                return ResourceManager.GetString("Quit_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        public static string Rename_caption {
            get {
                return ResourceManager.GetString("Rename_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename....
        /// </summary>
        public static string Rename_dot {
            get {
                return ResourceManager.GetString("Rename_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail, please check if the name is used..
        /// </summary>
        public static string Rename_fail {
            get {
                return ResourceManager.GetString("Rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input new file name.
        /// </summary>
        public static string Rename_message {
            get {
                return ResourceManager.GetString("Rename_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renamed to.
        /// </summary>
        public static string Rename_to {
            get {
                return ResourceManager.GetString("Rename_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string Save_success {
            get {
                return ResourceManager.GetString("Save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the keywords.
        /// </summary>
        public static string Search_message {
            get {
                return ResourceManager.GetString("Search_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share by Cool Editor.
        /// </summary>
        public static string Share_by_cooleditor {
            get {
                return ResourceManager.GetString("Share_by_cooleditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this file via:.
        /// </summary>
        public static string Share_caption {
            get {
                return ResourceManager.GetString("Share_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share....
        /// </summary>
        public static string Share_dot {
            get {
                return ResourceManager.GetString("Share_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are several methods for you to share code files..
        /// </summary>
        public static string Share_message {
            get {
                return ResourceManager.GetString("Share_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong, :-(.
        /// </summary>
        public static string Something_wrong {
            get {
                return ResourceManager.GetString("Something_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onedrive support added, disable sync when launch the app, some small bugs.
        /// </summary>
        public static string update_20140819 {
            get {
                return ResourceManager.GetString("update_20140819", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller Title Size for larger usable area, update ACE Editor..
        /// </summary>
        public static string update_20141116 {
            get {
                return ResourceManager.GetString("update_20141116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to Dropbox.
        /// </summary>
        public static string upload_dropbox {
            get {
                return ResourceManager.GetString("upload_dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to Onedrive.
        /// </summary>
        public static string upload_onedrive {
            get {
                return ResourceManager.GetString("upload_onedrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        public static string what_new {
            get {
                return ResourceManager.GetString("what_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, a problem occurred the last time you ran Cool Editor. Would you like to let Cool Editor send an email to report it? :-).
        /// </summary>
        public static string would_you_like_error_report {
            get {
                return ResourceManager.GetString("would_you_like_error_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using WP8.0 There are bugs that you may found during editing code, the Enter key is sometimes not responding, backspace deletes two 2 chars at one press. I am currently working on it..
        /// </summary>
        public static string WP80Bug {
            get {
                return ResourceManager.GetString("WP80Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using WP8.1 There is a bug that you may found during editing code, the Enter key is sometimes not responding. You can press other keys and then Enter key, I am currently working on it..
        /// </summary>
        public static string WP81Bug {
            get {
                return ResourceManager.GetString("WP81Bug", resourceCulture);
            }
        }
    }
}
